### ISSUE TITLE
Subscribing to state updates?

### ISSUE THREAD

**Issue by nightscape** [thehonesttech/zio-entity#72]
Hi @thehonesttech, I'm experimenting with using zio-entity for writing a (JSON-) document based digital twin.
I have several methods that modify the state (JSON) of the digital twin and would now like to subscribe to the state changes from another component, optimally with a ZStream (or a ZManaged[ZStream] for subscription cancelling). I found several occurrences of Streams in the code base, but afaiu none of them is for subscribing to the state changes.
Is this something that I should implement myself, or would it be useful in general, or am I missing/misunderstanding something completely?

**Comment by thehonesttech** [comment]
State is feed by events and you can subscribe on event stream with a readside subscription.
Commands generates events, events change the state. You can try to reduce at minimum the logic in the events => state (fold) function having dumb events that basically just describe the change in the state. If that does not suit you, you can always  create a state storage that wraps another storage
